name: Backend Plugin Testing

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  backend_plugins:
    runs-on: ubuntu-latest
    env:
      DB_PORT: '3307'
    continue-on-error: true
    strategy:
      matrix:
        archivesspace_version: [v4.0.0, v4.1.0]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setup ArchivesSpace ${{ matrix.archivesspace_version }}
      uses: Smithsonian/caas-aspace-services/.github/actions/setup_archivesspace@main
      with:
        archivesspace-version: ${{ matrix.archivesspace_version }}
        db-port: ${{ env.DB_PORT }}
        plugin: ${{ github.event.repository.name }}

    - name: Bootstrap ArchivesSpace
      uses: Smithsonian/caas-aspace-services/.github/actions/bootstrap@main
      with:
        backend: 'true'

    - name: Run Backend plugin tests
      run: |
        ./build/run backend:test -Dspec="../../plugins/${{ github.event.repository.name }}/backend"
